# Generated by Django 4.1.7 on 2023-03-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natthan_Django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='Kenya', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
