# Generated by Django 4.1.7 on 2023-03-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Natthan_Django', '0002_student_country_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
    ]
