# Generated by Django 4.1.7 on 2023-03-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Natthan_Django', '0004_student_idnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='idnumber',
            new_name='amount',
        ),
    ]
